# Generated by Django 4.0.4 on 2022-04-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
    ]
